### ISSUE TITLE
XC9572XLTQG100

### ISSUE THREAD

**Issue by xiphias256** [vossi1/v6510#1]
Can't find this part - XC9572XLTQG100
Is it supposed to be XC9572XL-7TQG100C? (7.5 ns)

Other possible parts is XC9572XL-5TQG100C (5 ns) and XC9572XL-10TQG100C (10 ns)

**Comment by vossi1** [comment]
Hello, I used a 7,5 ns commercial temperature range CPLD. You can also use the industrial 7I. The 10 ns version is untested - but should work. I already had these from the Snark Barker MCA and the PlaidBib cards.
The Xilinx order code is: XC9572XL-7TQ100C
You can read it on the bottom photo: https://github.com/vossi1/v6510/blob/master/v6510_v2_photo2.jpg
In the last line is the "7C"
